### ISSUE TITLE
add dash to /etc/shells

### ISSUE THREAD

**Issue by gumblex** [AOSC-Dev/aosc-aaa#4]
Add `/bin/dash` to /etc/shells.

Is `screen` and `tmux` also valid?

**Comment by MingcongBai** [comment]
> Is screen and tmux also valid?

Using `screen` or `tmux` as shells you meant?!

**Comment by gumblex** [comment]
I see them in Debian's.

**Comment by MingcongBai** [comment]
Huh, that's interesting.

**Comment by LionNatsu** [comment]
Smart way to start a daemon, uh?

**Comment by MingcongBai** [comment]
> Smart way to start a daemon, uh?

I believe you have misunderstood the meaning of `/etc/shells`...

**Comment by LionNatsu** [comment]
@MingcongBai You're right.

So the true goal is to simply provide a list of screen-like applications?

**Comment by MingcongBai** [comment]
@LionNatsu This file defines all the shells that could be allowed to serve as login shells.

**Comment by gumblex** [comment]
So, fix the first question first?

**Comment by MingcongBai** [comment]
One sec.
